<?xml version="1.0" encoding="UTF-8"?>
<project
		xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
		xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>io.github.linkedfactory</groupId>
		<artifactId>linkedfactory-parent</artifactId>
		<version>1.3.0-SNAPSHOT</version>
		<relativePath>../../pom.xml</relativePath>
	</parent>

	<artifactId>io.github.linkedfactory.service</artifactId>

	<dependencies>
		<dependency>
			<groupId>net.enilink.platform</groupId>
			<artifactId>net.enilink.platform.feature</artifactId>
			<version>${enilink.version}</version>
			<type>pom</type>
			<exclusions>
				<exclusion>
					<groupId>org.opendaylight.controller</groupId>
					<artifactId>scala3-library</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.eclipse.paho</groupId>
			<artifactId>org.eclipse.paho.client.mqttv3</artifactId>
			<version>1.2.5</version>
		</dependency>
		<dependency>
			<groupId>io.github.linkedfactory</groupId>
			<artifactId>io.github.linkedfactory.core</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>org.osgi</groupId>
			<artifactId>osgi.core</artifactId>
			<version>8.0.0</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.osgi</groupId>
			<artifactId>org.osgi.service.component</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.osgi</groupId>
			<artifactId>org.osgi.service.component.annotations</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.osgi</groupId>
			<artifactId>org.osgi.service.cm</artifactId>
			<!-- required at runtime by Apache HTTP Client and therefore not provided -->
		</dependency>
		<dependency>
			<groupId>org.osgi</groupId>
			<artifactId>org.osgi.service.event</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>com.rgi-corp</groupId>
			<artifactId>ww-geo-coords</artifactId>
			<version>1.0</version>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-csv</artifactId>
			<version>1.14.1</version>
		</dependency>
		<dependency>
			<groupId>org.webjars.npm</groupId>
			<artifactId>slickgrid</artifactId>
			<version>5.18.6</version>
			<scope>provided</scope>
			<exclusions>
				<exclusion>
					<groupId>org.webjars.npm</groupId>
					<artifactId>jquery</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.webjars.npm</groupId>
			<artifactId>select2</artifactId>
			<version>4.1.0</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.webjars.npm</groupId>
			<artifactId>moment</artifactId>
			<version>2.30.1</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.webjars.npm</groupId>
			<artifactId>moment-timezone</artifactId>
			<version>0.6.2</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.webjars.npm</groupId>
			<artifactId>eonasdan-bootstrap-datetimepicker</artifactId>
			<version>4.17.49</version>
			<scope>provided</scope>
			<exclusions>
				<exclusion>
					<groupId>org.webjars.npm</groupId>
					<artifactId>jquery</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.webjars.npm</groupId>
			<artifactId>simplify-js</artifactId>
			<version>1.2.4</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.webjars.npm</groupId>
			<artifactId>d3</artifactId>
			<version>7.9.0</version>
			<scope>provided</scope>
			<exclusions>
				<exclusion>
					<groupId>*</groupId>
					<artifactId>*</artifactId>
				</exclusion></exclusions>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.13.2</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.mockito</groupId>
			<artifactId>mockito-core</artifactId>
			<version>5.23.0</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.openjdk.jmh</groupId>
			<artifactId>jmh-core</artifactId>
			<version>1.37</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.openjdk.jmh</groupId>
			<artifactId>jmh-generator-annprocess</artifactId>
			<version>1.37</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>net.liftweb</groupId>
			<artifactId>lift-testkit_${scala.major.version}</artifactId>
			<version>4.0.0</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>jakarta.servlet</groupId>
			<artifactId>jakarta.servlet-api</artifactId>
			<version>6.1.0</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>io.github.pcmind</groupId>
			<artifactId>leveldb</artifactId>
			<version>1.2</version>
			<exclusions>
				<exclusion>
					<groupId>com.google.guava</groupId>
					<artifactId>*</artifactId>
				</exclusion>
			</exclusions>
			<scope>provided</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<!-- skip Java compilation as it is already executed via Scala plugin -->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<skip>true</skip>
				</configuration>
				<!-- this is required for older Maven versions that don't recognize skip -->
				<executions>
					<execution>
						<id>default-compile</id>
						<phase>none</phase>
					</execution>
					<execution>
						<id>default-testCompile</id>
						<phase>none</phase>
					</execution>
				</executions>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<executions>
					<execution>
						<id>embed-webjars</id>
						<phase>compile</phase>
					</execution>
					<execution>
						<id>copy-libraries</id>
						<phase>validate</phase>
						<configuration>
							<includeGroupIds>org.eclipse.paho,com.rgi-corp,org.apache.commons</includeGroupIds>
							<excludeTransitive>true</excludeTransitive>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

	<profiles>
		<profile>
			<id>jmh</id>
			<properties>
				<jmh.includes>io.github.linkedfactory.service.benchmark.KvinIngestionBenchmark</jmh.includes>
				<jmh.result.format>json</jmh.result.format>
				<jmh.result.file>${project.build.directory}/jmh-result.json</jmh.result.file>
				<jmh.warmups>3</jmh.warmups>
				<jmh.measurements>5</jmh.measurements>
				<jmh.forks>2</jmh.forks>
				<jmh.temp.root></jmh.temp.root>
			</properties>
			<build>
				<plugins>
					<plugin>
						<groupId>org.codehaus.mojo</groupId>
						<artifactId>exec-maven-plugin</artifactId>
						<version>3.5.0</version>
						<configuration>
							<executable>${java.home}/bin/java</executable>
							<classpathScope>test</classpathScope>
							<arguments>
								<argument>-Djmh.temp.root=${jmh.temp.root}</argument>
								<argument>-cp</argument>
								<classpath/>
								<argument>org.openjdk.jmh.Main</argument>
								<argument>${jmh.includes}</argument>
								<argument>-wi</argument>
								<argument>${jmh.warmups}</argument>
								<argument>-i</argument>
								<argument>${jmh.measurements}</argument>
								<argument>-f</argument>
								<argument>${jmh.forks}</argument>
								<argument>-rf</argument>
								<argument>${jmh.result.format}</argument>
								<argument>-rff</argument>
								<argument>${jmh.result.file}</argument>
							</arguments>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
</project>
